import type { GeneratedIdea } from '@/types/generated_idea';

export default function GeneratedIdeaComponent({
    generated_idea,
}: {
    generated_idea: GeneratedIdea;
}) {
    return (
        <div className="mb-4 space-y-1.5 rounded-xl bg-gray-800 p-4">
            <div className="text-xl underline">
                <strong>{generated_idea.startup_name}</strong>
            </div>
            <div>
                <strong>Summary:</strong>&nbsp;
                {generated_idea.summary}
            </div>
            <div>
                <strong>Investor Pitch:</strong>&nbsp;
                {generated_idea.investor_pitch}
            </div>
            <div>
                <strong>Price Tiers:</strong>
                <div className="grid grid-cols-1 gap-2 lg:grid-cols-3">
                    {generated_idea.price_tiers.map((price_tier) => (
                        <div
                            key={price_tier.id}
                            className="mb-1 rounded-md bg-gray-900 p-2"
                        >
                            <strong>{price_tier.name}</strong>: $
                            {(price_tier.price_cents / 100).toFixed(2)}
                            /month
                            <br />
                            <div className="">{price_tier.description}</div>
                        </div>
                    ))}
                </div>
            </div>
            <div>
                <strong>Testimonials:</strong>
                <div className="space-y-2">
                    {generated_idea.testimonials.map((testimonial) => (
                        <div
                            key={testimonial.id}
                            className="rounded-md bg-gray-900 p-2"
                        >
                            "{testimonial.comment}"
                            <br />
                            &mdash; {testimonial.author ?? 'Anonymous'}
                        </div>
                    ))}
                </div>
            </div>
            <div>
                Generated by <strong>{generated_idea.model}</strong> from{' '}
                <strong>{generated_idea.user.name}</strong>'s suggestion
            </div>
        </div>
    );
}
